In [1]:
# numpy

In [2]:
import numpy as np

In [3]:
# Cria uma matriz unidimensional

mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [5]:
# Criar array com um tipo especifico
# Cria o array como float de 64 bits

mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [6]:
# Mudar o tipo de array
# Podemos transformar tipos de dados de array

mtnew = np.array([1,4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)

# Quando trasnformamos de float para int os valores são truncados

mtnewint = mtnew.astype(np.int32)
print(mtnewint)


[ 1.        4.        3.6      -5.1       9.42      4.999999]
[ 1  4  3 -5  9  4]


In [7]:
# Podemos fazer o inverso também

mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [8]:
# Mais de uma dimensão
# Cria uma matriz bidimensional

mt7 = np.array([[7, 2, 23], [12, 27, 4], [5, 34, 23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [3]:
# Cria arrays vazios tipificados
# empty siginifica que não são inicializados, não que são vazios

vazio = np.empty([3, 2], dtype = int)
print(vazio)
print('-------')

# Cria uma matriz 4x3 com valores zero

zeros = np.zeros([4, 3])
print(zeros)
print('-------')

# Com valores igual a um

um = np.ones([5, 7])
print(um)
print('-------')

# Cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero

diagonal = np.eye(5)
print(diagonal)
print('-------')


[[-1549367968         472]
 [          0           0]
 [          1    23533924]]
-------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-------


In [4]:
# Valores aleatórios entre zero e um

ale = np.random.random((5))
print(ale)
print('-------')

# Valores aleatórios distr. normal contendo negativos

ale2 = np.random.randn((5))
print(ale2)
print('-------')

#Valores aleatórios 3 x 4

ale3 = (10*np.random.random((3, 4)))
print(ale3)
print('-------')


[0.59293567 0.31837653 0.93398314 0.51736321 0.109311  ]
-------
[ 0.5958721   1.05749446  2.33437065 -0.38925184 -0.18286624]
-------
[[0.30716398 5.66228046 3.25395052 9.12309286]
 [5.4178406  7.57594166 4.43501118 4.07320625]
 [9.33590638 0.89879559 6.12926095 2.73666001]]
-------


In [6]:
# Outra forma de gerar aleatórios
# uso de semente

gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)
print('-------')


[0.51182162 0.9504637  0.14415961]
-------


In [7]:
# Unique remove repetições

j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)


[11 12 13 14 15 16 17 18 19 20]


In [11]:
# Funções especificas
# Cria a matriz bidimensional k

k = np.array([[17, 22, 43], [27, 25, 14], [15, 24, 32]])

# Mostra a matriz k

print(k)

# Mostra um elemento específico da matriz k

print(k[0][1])

# Mostra o tamanho das dimensões da matriz k

print(k.shape)


[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [12]:
# Funções Matemáticas
# Mostra o maior valor da matriz k

print(k.max())

# Mostra o menos valor da matriz k

print(k.min())

# Mostra a soma dos valores da matriz k

print(k.sum())

# Mostra o valor da media dos valores da matriz k

print(k.mean())

# Mostra o valor de desvio padrão ( standart desviation) dos valores da matriz k

print(k.std())


43
14
219
24.333333333333332
8.615231988880057


In [13]:
# Funções universáis, aplicadas a todos os elementos
# Mostra o valor da raiz quadrada do todos os elementos

k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

# Mostra o valor do exponencial de todos os elementos

print(np.exp(k1))


[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [14]:
# Extração de elementos

m = np.array([1, 2, 3, 4, 5, 6])

# Mostra o elemento da posição 2

print(m[1])
print('--------')

# Mostra o array criado a partir da posição 0, dois elementos

print(m[0:2])
print('--------')

# Mostra o array criado a apartir da 2a posição

print(m[1:])
print('--------')

# Mostra o array criado a partir da antepenultima
#Posição até o final

print(m[-3:])


2
--------
[1 2]
--------
[2 3 4 5 6]
--------
[4 5 6]


In [26]:
# Extração de linhas e colunas

l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print('--------')

# Primeira linha todas as colunas

l_linha_1 = l[0, :]
print(l_linha_1)
print('--------')

# segunda linha

l_linha_2 = l[1, :]
print(l_linha_2)
print('--------')

# terceira linha

l_linha_3 = l[2, :]
print(l_linha_3)
print('--------')

# Todas as linhas, primeira coluna

l_coluna_1 = l[:, 0]
print(l_coluna_1)
print('--------')

# Todas as linhas, segunda coluna

l_coluna_2 = l[:, 1]
print(l_coluna_2)


[[4 5]
 [6 1]
 [7 4]]
--------
[4 5]
--------
[6 1]
--------
[7 4]
--------
[4 6 7]
--------
[5 1 4]


In [27]:
# Adição e multiplicação de matrizes

n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n+o
print(res1)
print('--------')

res2 = n*o
print(res2)
print('--------')

p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q)


[[2 3]
 [4 5]]
--------
[[1 2]
 [3 4]]
--------
[[3 3]
 [5 5]
 [7 7]]


In [28]:
# Transposição, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linha e 5 colunas

f = np.arange(15).reshape((3, 5))

# Mostras as matrizes transporta entre linha e coluna

print(f)
print('--------')

s = f.T
print(s)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [29]:
# Outra forma de fazer, mesmo resultado

r = np.arange(15).reshape((3, 5))
print(r)
print('-------')

# Rearranja um conjunto de 15 elementos
# Mostra a matrizes transposta entre linha e coluna

s = r.transpose((1, 0))
print(s)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [30]:
# Expressões lógicas
# Usando where
# Criando matriz com valores aleatórios positivos e negativos

v = np.random.randn(4, 4)
print(v)
print('-------')

# Criando matriz com valores booleanos baseado na array v

x = (v > 0)
print(x)
print('-------')

# Criando matriz com valores -1 e 1 baseado nos valores do array x

z = np.where(x > 0, 1, -1)
print(z)
print('-------')


[[ 0.74355321 -0.52536633  0.91986322  1.33401583]
 [ 0.19700507  0.68355855 -0.5546004  -0.10008003]
 [-1.17321306 -0.4446962   0.32260067 -0.98945551]
 [ 0.49817024  0.20970081 -1.14976577  0.09860001]]
-------
[[ True False  True  True]
 [ True  True False False]
 [False False  True False]
 [ True  True False  True]]
-------
[[ 1 -1  1  1]
 [ 1  1 -1 -1]
 [-1 -1  1 -1]
 [ 1  1 -1  1]]
-------
